const LOJA='https://www.minhaloja.natura.com/consultoria/danielaportilho?marca=natura';
const WHATS='https://wa.me/5511984181351';

// ETAPA 4 — VITRINE DE CONVERSÃO
// Valores conferidos em 05/10/2026 nas páginas oficiais da Natura.
// Promoções e estoque mudam: revise estes campos periodicamente.
const OFERTAS=[
 {selo:'MAIS VENDIDO • -26%',titulo:'Kaiak 21K Masculino 100 ml',descricao:'Frescor aromático com gengibre e âmbar. Destaque atual da perfumaria masculina.',linha:'Kaiak',tipo:'Perfumaria',de:'R$ 189,90',por:'R$ 139,90',desconto:'26% OFF',imagem:'assets/beleza-botanica.png',posicao:'72% 22%'},
 {selo:'OFERTA • -40%',titulo:'Essencial Oud Masculino 100 ml',descricao:'Deo parfum intenso com oud e copaíba, indicado para ocasiões especiais.',linha:'Essencial',tipo:'Perfumaria',de:'R$ 289,90',por:'R$ 173,94',desconto:'40% OFF',imagem:'assets/beleza-botanica.png',posicao:'78% 22%'},
 {selo:'MAIS VENDIDO • -46%',titulo:'Tododia Maçã Caramelada e Baunilha',descricao:'Creme nutritivo corporal com perfil adocicado, entre os destaques atuais de corpo e banho.',linha:'Tododia',tipo:'Corpo & banho',de:'R$ 78,90',por:'R$ 42,61',desconto:'46% OFF',imagem:'assets/beleza-botanica.png',posicao:'23% 74%'},
 {selo:'MAIS VENDIDO • -60%',titulo:'Ekos Castanha Hidratante Corporal',descricao:'Hidratação corporal da linha Castanha, um clássico de Natura Ekos.',linha:'Ekos',tipo:'Corpo & banho',de:'R$ 88,90',por:'R$ 35,56',desconto:'60% OFF',imagem:'assets/beleza-botanica.png',posicao:'18% 75%'},
 {selo:'MAIS VENDIDO • -50%',titulo:'Papai e Bebê Água de Colônia 50 ml',descricao:'Fragrância delicada da linha Papai e Bebê, em destaque na seleção atual de mais vendidos.',linha:'Papai e Bebê',tipo:'Família',de:'R$ 53,50',por:'R$ 26,75',desconto:'50% OFF',imagem:'assets/beleza-botanica.png',posicao:'70% 76%'},
 {selo:'PRESENTE • -10%',titulo:'Presente Ekos Cacau Mãos e Lábios',descricao:'Kit com dois produtos para um presente acessível e com apresentação especial.',linha:'Ekos',tipo:'Presentes',de:'R$ 79,90',por:'R$ 71,90',desconto:'10% OFF',imagem:'assets/beleza-botanica.png',posicao:'79% 76%'}
];
const grid=document.getElementById('offerGrid');
if(grid){grid.innerHTML=OFERTAS.map((o,i)=>`<article class="offer-card"><div class="offer-image"><img src="${o.imagem}" alt="Composição visual de beleza para ${o.titulo}" loading="lazy" style="object-position:${o.posicao}"><span class="offer-tag">${o.selo}</span></div><div class="offer-body"><h3>${o.titulo}</h3><div class="product-meta"><span>${o.linha}</span><span>${o.tipo}</span></div><p>${o.descricao}</p><div class="price-row"><span class="old-price">${o.de}</span><strong class="current-price">${o.por}</strong><span class="discount">${o.desconto}</span></div><p class="price-note">Preço de referência consultado em 05/10/2026. Confirme na loja.</p><div class="card-actions"><a class="btn track-store" data-product="${o.titulo}" target="_blank" rel="noopener" href="${LOJA}">Comprar com a Dani</a><a class="btn-secondary track-whats" data-product="${o.titulo}" target="_blank" rel="noopener" href="${WHATS}?text=${encodeURIComponent('Oi Dani! Vi '+o.titulo+' no seu site e quero saber mais.')}">Tirar dúvida</a></div></div></article>`).join('')}

// Métricas simples no navegador. Preparado também para Google Analytics via dataLayer.
function track(type,label){try{const key='dani_'+type;localStorage.setItem(key,String((+localStorage.getItem(key)||0)+1));window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:type,item_name:label||''});}catch(e){}}
document.addEventListener('click',e=>{const a=e.target.closest('a');if(!a)return;if(a.classList.contains('track-store')||a.href.includes('minhaloja.natura.com'))track('click_loja',a.dataset.product||a.textContent.trim());if(a.classList.contains('track-whats')||a.href.includes('wa.me'))track('click_whatsapp',a.dataset.product||a.textContent.trim());});
const menu=document.querySelector('.menu'),nav=document.querySelector('.navlinks');menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open);menu.textContent=open?'✕':'☰'});document.querySelectorAll('.navlinks a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu?.setAttribute('aria-expanded','false');if(menu)menu.textContent='☰'}));document.getElementById('year').textContent=new Date().getFullYear();
